apiVersion: apps/v1
kind: Deployment
metadata:
  name: no-antiaffinity-deploy-bad
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: nginx
        image: nginx
      # Pas d'anti-affinité
