cat <<EOF | kubectl apply -f - || echo "Test réussi - la création a échoué comme prévu"
apiVersion: v1
kind: Secret
metadata:
  name: test-secret
type: Opaque
data:
  password: dmFsaWQtcGFzc3dvcmQ=  # "valid-password" en base64
EOF
