apiVersion: apps/v1
kind: Deployment
metadata:
  name: no-pdb-deploy-bad
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: nginx
        image: nginx
  # Pas de PodDisruptionBudget
