apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod-bad
spec:
  volumes:
  - name: bad-vol
    hostPath:
      path: /etc  # Violation
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: bad-vol
      mountPath: /host-etc
